-- Caisse Familiale / Solidarity
-- Supabase PostgreSQL migration
-- Run once in Supabase Dashboard -> SQL Editor.
-- This script is intentionally idempotent.
-- Create Auth users separately in Authentication -> Users:
--   admin@tontine.local / TontineAdmin2026!
--   users@tontine.local / TontineUsers2026!

create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  open_id text unique not null,
  name text,
  email text,
  login_method text default 'supabase' not null,
  role text default 'user' not null check (role in ('user', 'admin')),
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  last_signed_in timestamptz default now() not null
);

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  full_name varchar(160) not null,
  phone varchar(40),
  email varchar(320),
  joined_at timestamptz default now() not null,
  is_active boolean default true not null,
  notes text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete restrict,
  payment_date timestamptz not null,
  amount integer not null check (amount > 0),
  payment_method varchar(40) default 'ESPECES' not null,
  reference varchar(120),
  observation text,
  recorded_by uuid not null references public.users(id) on delete restrict,
  created_at timestamptz default now() not null
);

create table if not exists public.payment_allocations (
  id bigint generated by default as identity primary key,
  payment_transaction_id bigint not null references public.payment_transactions(id) on delete cascade,
  member_id bigint not null references public.members(id) on delete restrict,
  month_key varchar(7) not null check (month_key ~ '^[0-9]{4}-[0-9]{2}$'),
  amount integer not null check (amount > 0),
  created_at timestamptz default now() not null,
  unique (payment_transaction_id, month_key)
);

create table if not exists public.cash_transactions (
  id bigint generated by default as identity primary key,
  direction text not null check (direction in ('IN', 'OUT')),
  source_type varchar(40) not null,
  source_id bigint,
  amount integer not null check (amount > 0),
  transaction_date timestamptz not null,
  description text,
  created_by uuid not null references public.users(id) on delete restrict,
  created_at timestamptz default now() not null
);

create table if not exists public.withdrawals (
  id bigint generated by default as identity primary key,
  withdrawal_date timestamptz not null,
  amount integer not null check (amount > 0),
  category text not null check (category in ('SANTE','URGENCE','DECES','EDUCATION','EVENEMENT_FAMILIAL','AIDE_FAMILIALE','DEPLACEMENT','AUTRE')),
  beneficiary varchar(160),
  motif varchar(255) not null,
  description text,
  payment_method varchar(40) default 'ESPECES' not null,
  reference varchar(120),
  observation text,
  created_by uuid not null references public.users(id) on delete restrict,
  created_at timestamptz default now() not null
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title varchar(180) not null,
  body text not null,
  created_by uuid not null references public.users(id) on delete restrict,
  published_at timestamptz default now() not null
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  title varchar(180) not null,
  body text not null,
  read_at timestamptz,
  created_at timestamptz default now() not null
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  action varchar(40) not null,
  entity_type varchar(80) not null,
  entity_id bigint,
  old_value jsonb,
  new_value jsonb,
  user_id uuid references public.users(id) on delete set null,
  created_at timestamptz default now() not null
);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  setting_key varchar(80) unique not null,
  setting_value varchar(255) not null,
  description text,
  updated_by uuid references public.users(id) on delete set null,
  updated_at timestamptz default now() not null
);

insert into public.settings (setting_key, setting_value)
values ('monthly_contribution', '1000')
on conflict (setting_key) do nothing;

create index if not exists payment_transactions_member_date_idx on public.payment_transactions(member_id, payment_date desc);
create index if not exists payment_allocations_member_month_idx on public.payment_allocations(member_id, month_key);
create index if not exists cash_transactions_date_idx on public.cash_transactions(transaction_date desc);
create index if not exists withdrawals_date_idx on public.withdrawals(withdrawal_date desc);
create index if not exists announcements_date_idx on public.announcements(published_at desc);
create index if not exists audit_logs_date_idx on public.audit_logs(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists members_set_updated_at on public.members;
create trigger members_set_updated_at before update on public.members for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, open_id, name, email, login_method, role)
  values (
    new.id,
    new.id::text,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
    new.email,
    'supabase',
    case when coalesce(new.raw_user_meta_data ->> 'role', '') = 'admin' or new.email = 'admin@tontine.local' then 'admin' else 'user' end
  )
  on conflict (id) do update set
    name = excluded.name,
    email = excluded.email,
    last_signed_in = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update on auth.users for each row execute function public.handle_new_auth_user();

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.users where id = auth.uid() and role = 'admin')
      or coalesce((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin', false);
$$;

create or replace function public.monthly_contribution()
returns integer
language sql
stable
security invoker
as $$
  select coalesce((select setting_value::integer from public.settings where setting_key = 'monthly_contribution'), 1000);
$$;

create or replace function public.month_key(value timestamptz)
returns varchar(7)
language sql
immutable
as $$ select to_char(value at time zone 'UTC', 'YYYY-MM'); $$;

create or replace function public.add_months(key varchar(7), amount integer)
returns varchar(7)
language sql
immutable
as $$ select to_char((to_date(key || '-01', 'YYYY-MM-DD') + make_interval(months => amount))::date, 'YYYY-MM'); $$;

create or replace function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  entity_id_value bigint;
begin
  if tg_table_name = 'settings' then
    entity_id_value := null;
  elsif tg_op = 'DELETE' then
    entity_id_value := old.id;
  else
    entity_id_value := new.id;
  end if;
  insert into public.audit_logs(action, entity_type, entity_id, old_value, new_value, user_id)
  values (
    tg_op,
    tg_table_name,
    entity_id_value,
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end,
    auth.uid()
  );
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists members_audit on public.members;
create trigger members_audit after insert or update or delete on public.members for each row execute function public.audit_row_change();
drop trigger if exists payments_audit on public.payment_transactions;
create trigger payments_audit after insert or update or delete on public.payment_transactions for each row execute function public.audit_row_change();
drop trigger if exists withdrawals_audit on public.withdrawals;
create trigger withdrawals_audit after insert or update or delete on public.withdrawals for each row execute function public.audit_row_change();
drop trigger if exists announcements_audit on public.announcements;
create trigger announcements_audit after insert or update or delete on public.announcements for each row execute function public.audit_row_change();
drop trigger if exists settings_audit on public.settings;
create trigger settings_audit after insert or update or delete on public.settings for each row execute function public.audit_row_change();

create or replace function public.allocate_payment(
  p_member_id bigint,
  p_amount integer,
  p_payment_date timestamptz,
  p_payment_method varchar default 'ESPECES',
  p_reference varchar default null,
  p_observation text default null,
  p_forced_month varchar default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  member_row public.members%rowtype;
  payment_id bigint;
  remaining integer := p_amount;
  contribution integer := public.monthly_contribution();
  key varchar(7);
  paid integer;
  applied integer;
  allocation_json jsonb := '[]'::jsonb;
  current_month varchar(7) := public.month_key(p_payment_date);
  actor uuid := auth.uid();
begin
  if actor is null then raise exception 'Utilisateur non authentifié'; end if;
  if not public.current_user_is_admin() then raise exception 'Droits administrateur requis'; end if;
  if p_amount is null or p_amount <= 0 then raise exception 'Le montant doit être positif'; end if;
  select * into member_row from public.members where id = p_member_id and is_active = true;
  if not found then raise exception 'Membre introuvable ou inactif'; end if;

  insert into public.payment_transactions(member_id, payment_date, amount, payment_method, reference, observation, recorded_by)
  values (p_member_id, p_payment_date, p_amount, p_payment_method, p_reference, p_observation, actor)
  returning id into payment_id;

  if p_forced_month is not null then
    key := p_forced_month;
    select coalesce(sum(amount), 0) into paid from public.payment_allocations where member_id = p_member_id and month_key = key;
    if paid > 0 then raise exception 'Cette échéance possède déjà un paiement'; end if;
    applied := least(contribution, remaining);
    insert into public.payment_allocations(payment_transaction_id, member_id, month_key, amount) values (payment_id, p_member_id, key, applied);
    allocation_json := allocation_json || jsonb_build_array(jsonb_build_object('monthKey', key, 'amount', applied));
    remaining := remaining - applied;
  else
    for key in select to_char((date_trunc('month', member_row.joined_at at time zone 'UTC') + (n || ' months')::interval)::date, 'YYYY-MM') from generate_series(0, 239) n where to_char((date_trunc('month', member_row.joined_at at time zone 'UTC') + (n || ' months')::interval)::date, 'YYYY-MM') <= current_month
      union all
      select public.add_months(current_month, n) from generate_series(1, 120) n
    loop
      exit when remaining <= 0;
      select coalesce(sum(amount), 0) into paid from public.payment_allocations where member_id = p_member_id and month_key = key;
      applied := least(greatest(contribution - paid, 0), remaining);
      if applied > 0 then
        insert into public.payment_allocations(payment_transaction_id, member_id, month_key, amount) values (payment_id, p_member_id, key, applied);
        allocation_json := allocation_json || jsonb_build_array(jsonb_build_object('monthKey', key, 'amount', applied));
        remaining := remaining - applied;
      end if;
    end loop;
  end if;

  if remaining > 0 then raise exception 'Impossible d’affecter le montant aux échéances disponibles'; end if;
  insert into public.cash_transactions(direction, source_type, source_id, amount, transaction_date, description, created_by)
  values ('IN', 'PAYMENT', payment_id, p_amount, p_payment_date, 'Cotisation de ' || member_row.full_name, actor);
  return jsonb_build_object('paymentId', payment_id, 'memberName', member_row.full_name, 'allocation', allocation_json);
end;
$$;

create or replace function public.create_withdrawal(
  p_withdrawal_date timestamptz,
  p_amount integer,
  p_category text,
  p_motif varchar,
  p_beneficiary varchar default null,
  p_description text default null,
  p_payment_method varchar default 'ESPECES',
  p_reference varchar default null,
  p_observation text default null
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  actor uuid := auth.uid();
  withdrawal_id bigint;
  available integer;
begin
  if actor is null or not public.current_user_is_admin() then raise exception 'Droits administrateur requis'; end if;
  select coalesce(sum(case when direction = 'IN' then amount else -amount end), 0) into available from public.cash_transactions;
  if p_amount <= 0 or p_amount > available then raise exception 'Solde insuffisant ou montant invalide'; end if;
  insert into public.withdrawals(withdrawal_date, amount, category, beneficiary, motif, description, payment_method, reference, observation, created_by)
  values (p_withdrawal_date, p_amount, p_category, p_beneficiary, p_motif, p_description, p_payment_method, p_reference, p_observation, actor)
  returning id into withdrawal_id;
  insert into public.cash_transactions(direction, source_type, source_id, amount, transaction_date, description, created_by)
  values ('OUT', 'WITHDRAWAL', withdrawal_id, p_amount, p_withdrawal_date, p_motif, actor);
  return withdrawal_id;
end;
$$;

create or replace view public.member_situations as
with contribution as (select public.monthly_contribution() as amount),
paid as (select member_id, month_key, sum(amount)::integer as amount from public.payment_allocations group by member_id, month_key),
months as (
  select m.id as member_id, m.full_name, m.phone, m.email, m.joined_at, m.is_active, c.amount as contribution,
    to_char(gs.month_start::date, 'YYYY-MM') as month_key
  from public.members m cross join contribution c
  cross join lateral generate_series(date_trunc('month', m.joined_at), date_trunc('month', now()), interval '1 month') gs(month_start)
),
current_due as (
  select months.member_id, months.full_name, months.phone, months.email, months.joined_at, months.is_active, months.contribution,
    sum(greatest(months.contribution - coalesce(paid.amount, 0), 0))::integer as due_amount,
    sum(coalesce(paid.amount, 0))::integer as paid_amount,
    count(*) filter (where coalesce(paid.amount, 0) >= months.contribution)::integer as paid_months,
    count(*) filter (where coalesce(paid.amount, 0) > 0 and coalesce(paid.amount, 0) < months.contribution)::integer as partial_months,
    count(*) filter (where coalesce(paid.amount, 0) < months.contribution)::integer as late_months
  from months left join paid on paid.member_id = months.member_id and paid.month_key = months.month_key
  group by months.member_id, months.full_name, months.phone, months.email, months.joined_at, months.is_active, months.contribution
), advances as (
  select p.member_id, count(*)::integer as advance_months, max(p.month_key) as up_to_month
  from paid p where p.month_key > public.month_key(now()) and p.amount >= public.monthly_contribution() group by p.member_id
)
select d.*, coalesce(a.advance_months, 0) as advance_months, a.up_to_month,
  case when d.due_amount > 0 then 'RETARD' when coalesce(a.advance_months, 0) > 0 then 'AVANCE' else 'A_JOUR' end as status
from current_due d left join advances a using (member_id);

create or replace view public.family_summary as
select
  (select count(*) from public.members)::integer as total_members,
  (select count(*) from public.members where is_active)::integer as active_members,
  (select coalesce(sum(amount), 0) from public.cash_transactions where direction = 'IN')::integer as total_in,
  (select coalesce(sum(amount), 0) from public.cash_transactions where direction = 'OUT')::integer as total_out,
  (select coalesce(sum(amount), 0) from public.cash_transactions where direction = 'IN')::integer - (select coalesce(sum(amount), 0) from public.cash_transactions where direction = 'OUT')::integer as balance,
  (select coalesce(sum(due_amount), 0) from public.member_situations where is_active)::integer as arrears,
  (select count(*) from public.member_situations where status = 'RETARD' and is_active)::integer as late_members,
  (select count(*) from public.member_situations where status = 'A_JOUR' and is_active)::integer as up_to_date_members,
  (select count(*) from public.member_situations where status = 'AVANCE' and is_active)::integer as members_with_advance;

-- RLS: authenticated users can read family information; only admins can write financial/family data.
alter table public.users enable row level security;
alter table public.members enable row level security;
alter table public.payment_transactions enable row level security;
alter table public.payment_allocations enable row level security;
alter table public.cash_transactions enable row level security;
alter table public.withdrawals enable row level security;
alter table public.announcements enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;
alter table public.settings enable row level security;

do $$
declare t text; begin
  foreach t in array array['users','members','payment_transactions','payment_allocations','cash_transactions','withdrawals','announcements','notifications','audit_logs','settings'] loop
    execute format('drop policy if exists %I on public.%I', t || '_select_authenticated', t);
    execute format('drop policy if exists %I on public.%I', t || '_admin_insert', t);
    execute format('drop policy if exists %I on public.%I', t || '_admin_update', t);
    execute format('drop policy if exists %I on public.%I', t || '_admin_delete', t);
  end loop;
end $$;

create policy users_select_authenticated on public.users for select to authenticated using (true);
create policy users_admin_update on public.users for update to authenticated using (public.current_user_is_admin() or id = auth.uid()) with check (public.current_user_is_admin() or id = auth.uid());
create policy members_select_authenticated on public.members for select to authenticated using (true);
create policy members_admin_insert on public.members for insert to authenticated with check (public.current_user_is_admin());
create policy members_admin_update on public.members for update to authenticated using (public.current_user_is_admin()) with check (public.current_user_is_admin());
create policy members_admin_delete on public.members for delete to authenticated using (public.current_user_is_admin());
create policy payment_transactions_select_authenticated on public.payment_transactions for select to authenticated using (true);
create policy payment_allocations_select_authenticated on public.payment_allocations for select to authenticated using (true);
create policy cash_transactions_select_authenticated on public.cash_transactions for select to authenticated using (true);
create policy withdrawals_select_authenticated on public.withdrawals for select to authenticated using (true);
create policy withdrawals_admin_insert on public.withdrawals for insert to authenticated with check (public.current_user_is_admin());
create policy withdrawals_admin_update on public.withdrawals for update to authenticated using (public.current_user_is_admin()) with check (public.current_user_is_admin());
create policy withdrawals_admin_delete on public.withdrawals for delete to authenticated using (public.current_user_is_admin());
create policy announcements_select_authenticated on public.announcements for select to authenticated using (true);
create policy announcements_admin_insert on public.announcements for insert to authenticated with check (public.current_user_is_admin());
create policy announcements_admin_update on public.announcements for update to authenticated using (public.current_user_is_admin()) with check (public.current_user_is_admin());
create policy announcements_admin_delete on public.announcements for delete to authenticated using (public.current_user_is_admin());
create policy notifications_select_own on public.notifications for select to authenticated using (user_id = auth.uid() or public.current_user_is_admin());
create policy notifications_update_own on public.notifications for update to authenticated using (user_id = auth.uid() or public.current_user_is_admin()) with check (user_id = auth.uid() or public.current_user_is_admin());
create policy audit_logs_select_authenticated on public.audit_logs for select to authenticated using (true);
create policy settings_select_authenticated on public.settings for select to authenticated using (true);
create policy settings_admin_insert on public.settings for insert to authenticated with check (public.current_user_is_admin());
create policy settings_admin_update on public.settings for update to authenticated using (public.current_user_is_admin()) with check (public.current_user_is_admin());
create policy settings_admin_delete on public.settings for delete to authenticated using (public.current_user_is_admin());

-- Grant access to the views and functions used by the browser client.
grant select on public.member_situations, public.family_summary to authenticated;
grant execute on function public.monthly_contribution(), public.month_key(timestamptz), public.add_months(varchar, integer), public.allocate_payment(bigint, integer, timestamptz, varchar, varchar, text, varchar), public.create_withdrawal(timestamptz, integer, text, varchar, varchar, text, varchar, varchar, text) to authenticated;

comment on table public.members is 'Family members participating in the solidarity fund';
comment on table public.payment_allocations is 'One real payment can cover current, arrears, or future monthly dues';
comment on function public.allocate_payment is 'Records one payment and allocates it oldest unpaid month first, then future months';
